webtalk_init -webtalk_dir D:/vivado-code/CPU/CPU.sim/sim_1/behav/xsim/xsim.dir/IM_sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Dec 29 21:28:21 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "698b6528-6bfc-48e7-9b68-ceccaf7f5113" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2116ac13f7c644bea07e63a118ff517e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "20" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD A4-5000 APU with Radeon(TM) HD Graphics    " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1497 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "3.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "10 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.72_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "8556_KB" -context "xsim\\usage"
webtalk_transmit -clientid 640894344 -regid "" -xml D:/vivado-code/CPU/CPU.sim/sim_1/behav/xsim/xsim.dir/IM_sim_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/vivado-code/CPU/CPU.sim/sim_1/behav/xsim/xsim.dir/IM_sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/vivado-code/CPU/CPU.sim/sim_1/behav/xsim/xsim.dir/IM_sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
